name: Setup Android Emulator
description: 'Sets up and configures Android emulator for testing'

inputs:
  api-level:
    description: 'API level to use for the emulator'
    required: true
  profile:
    description: 'The profile to use for the emulator'
    required: true
  ram-size:
    description: 'The RAM size to use for the emulator'
    required: true
  cores:
    description: 'The number of cores to use for the emulator'
    required: true
  arch:
    description: 'The architecture to use for the emulator'
    required: true
  emulators:
    description: 'The number of emulators to run'
    default: '1'
  emulator-build:
    description: 'The emulator build to use'

runs:
  using: "composite"
  steps:
    - name: Enable KVM
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: AVD cache
      uses: useblacksmith/cache@v5
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd-${{ inputs.api-level }}-${{ inputs.emulators }}-${{ inputs.cores }}-${{ inputs.profile }}-${{ inputs.ram-size }}-${{ inputs.arch }}-${{ inputs.emulator-build }}

    - name: Create AVD and Generate Snapshot for Caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ inputs.api-level }}
        target: google_apis_playstore
        arch: ${{ inputs.arch }}
        force-avd-creation: false
        emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none -no-metrics
        disable-animations: false
        profile: ${{ inputs.profile }}
        cores: ${{ inputs.cores }}
        ram-size: ${{ inputs.ram-size }}
        emulator-build: ${{ inputs.emulator-build }}
        script: |
          echo "Generated AVD snapshot for caching."
