export enum TransactionType {
  authorize = 'authorize',
  borrow = 'borrow',
  cancel = 'cancel',
  contract_interaction = 'contract interaction',
  deployment = 'deployment',
  deposit = 'deposit',
  dropped = 'dropped',
  execution = 'execution',
  purchase = 'purchase', // Rainbow-specific type
  receive = 'receive',
  repay = 'repay',
  sell = 'sell',
  send = 'send',
  trade = 'trade',
  withdraw = 'withdraw',
}

export default {
  authorize: 'authorize',
  borrow: 'borrow',
  cancel: 'cancel',
  contract_interaction: 'contract interaction',
  deployment: 'deployment',
  deposit: 'deposit',
  dropped: 'dropped',
  execution: 'execution',
  purchase: 'purchase',
  receive: 'receive',
  repay: 'repay',
  sell: 'sell',
  send: 'send',
  trade: 'trade',
  withdraw: 'withdraw',
};
