import { POLYMARKET_SPORTS_MARKET_TYPE } from '@/features/polymarket/constants';
import { PolymarketTeamInfo } from '@/features/polymarket/types';

export type SportsMarketType = (typeof POLYMARKET_SPORTS_MARKET_TYPE)[keyof typeof POLYMARKET_SPORTS_MARKET_TYPE];

type ImageOptimized = {
  id: string;
  imageUrlSource: string;
  imageUrlOptimized: string;
  imageSizeKbSource: number;
  imageSizeKbOptimized: number;
  imageOptimizedComplete: boolean;
  imageOptimizedLastUpdated: string;
  relID: number;
  field: string;
  relname: string;
};

type Category = {
  id: string;
  label: string;
  parentCategory: string;
  slug: string;
  publishedAt: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
};

type Tag = {
  id: string;
  label: string;
  slug: string;
  forceShow: boolean;
  publishedAt: string;
  createdBy: number;
  updatedBy: number;
  createdAt: string;
  updatedAt: string;
  forceHide: boolean;
  isCarousel: boolean;
};

type Chat = {
  id: string;
  channelId: string;
  channelName: string;
  channelImage: string;
  live: boolean;
  startTime: string;
  endTime: string;
};

type EventCreator = {
  id: string;
  creatorName: string;
  creatorHandle: string;
  creatorUrl: string;
  creatorImage: string;
  createdAt: string;
  updatedAt: string;
};

type Template = {
  id: string;
  eventTitle: string;
  eventSlug: string;
  eventImage: string;
  marketTitle: string;
  description: string;
  resolutionSource: string;
  negRisk: boolean;
  sortBy: string;
  showMarketImages: boolean;
  seriesSlug: string;
  outcomes: string;
};

export type RawPolymarketMarket = {
  id: string;
  question: string;
  conditionId: string;
  slug: string;
  twitterCardImage: string;
  resolutionSource: string;
  endDate: string;
  category: string;
  ammType: string;
  liquidity: string;
  sponsorName: string;
  sponsorImage: string;
  startDate: string;
  xAxisValue: string;
  yAxisValue: string;
  denominationToken: string;
  fee: string;
  image: string;
  icon: string;
  lowerBound: string;
  upperBound: string;
  description: string;
  outcomes: string;
  outcomePrices?: string;
  volume: string;
  active: boolean;
  marketType: string;
  formatType: string;
  lowerBoundDate: string;
  upperBoundDate: string;
  closed: boolean;
  marketMakerAddress: string;
  createdBy: number;
  updatedBy: number;
  createdAt: string;
  updatedAt: string;
  closedTime: string;
  wideFormat: boolean;
  new: boolean;
  mailchimpTag: string;
  featured: boolean;
  archived: boolean;
  resolvedBy: string;
  restricted: boolean;
  marketGroup: number;
  groupItemTitle: string;
  groupItemThreshold: string;
  questionID: string;
  umaEndDate: string;
  enableOrderBook: boolean;
  orderPriceMinTickSize: number;
  orderMinSize: number;
  umaResolutionStatus?: string;
  curationOrder: number;
  volumeNum: number;
  liquidityNum: number;
  endDateIso: string;
  startDateIso: string;
  umaEndDateIso: string;
  hasReviewedDates: boolean;
  readyForCron: boolean;
  commentsEnabled: boolean;
  volume24hr: number;
  volume1wk: number;
  volume1mo: number;
  volume1yr: number;
  gameStartTime: string;
  secondsDelay: number;
  clobTokenIds: string;
  disqusThread: string;
  shortOutcomes: string;
  teamAID: string;
  teamBID: string;
  umaBond: string;
  umaReward: string;
  fpmmLive: boolean;
  volume24hrAmm: number;
  volume1wkAmm: number;
  volume1moAmm: number;
  volume1yrAmm: number;
  volume24hrClob: number;
  volume1wkClob: number;
  volume1moClob: number;
  volume1yrClob: number;
  volumeAmm: number;
  volumeClob: number;
  liquidityAmm: number;
  liquidityClob: number;
  makerBaseFee: number;
  takerBaseFee: number;
  customLiveness: number;
  acceptingOrders: boolean;
  notificationsEnabled: boolean;
  score: number;
  imageOptimized: ImageOptimized;
  iconOptimized: ImageOptimized;
  events: PolymarketMarketEvent[];
  categories: Category[];
  tags: Tag[];
  creator: string;
  ready: boolean;
  funded: boolean;
  pastSlugs: string;
  readyTimestamp: string;
  fundedTimestamp: string;
  acceptingOrdersTimestamp: string;
  competitive: number;
  rewardsMinSize: number;
  rewardsMaxSpread: number;
  spread: number;
  automaticallyResolved: boolean;
  oneDayPriceChange?: number;
  oneHourPriceChange?: number;
  oneWeekPriceChange?: number;
  oneMonthPriceChange?: number;
  oneYearPriceChange?: number;
  lastTradePrice?: number;
  bestBid: number;
  bestAsk: number;
  automaticallyActive: boolean;
  clearBookOnStart: boolean;
  chartColor: string;
  seriesColor: string;
  showGmpSeries: boolean;
  showGmpOutcome: boolean;
  manualActivation: boolean;
  negRiskOther: boolean;
  negRisk: boolean;
  gameId?: number;
  groupItemRange: string;
  sportsMarketType: SportsMarketType;
  line: number;
  umaResolutionStatuses: string;
  pendingDeployment: boolean;
  deploying: boolean;
  deployingTimestamp: string;
  scheduledDeploymentTimestamp: string;
  rfqEnabled: boolean;
  eventStartTime: string;
};

export type PolymarketMarket = Omit<RawPolymarketMarket, 'clobTokenIds' | 'outcomes' | 'outcomePrices' | 'events'> & {
  clobTokenIds: string[];
  outcomes: string[];
  outcomePrices: string[];
  events: PolymarketMarketEvent[];
  color: string;
  secondaryColor: string | undefined;
};

type Collection = {
  id: string;
  ticker: string;
  slug: string;
  title: string;
  subtitle: string;
  collectionType: string;
  description: string;
  tags: string;
  image: string;
  icon: string;
  headerImage: string;
  layout: string;
  active: boolean;
  closed: boolean;
  archived: boolean;
  new: boolean;
  featured: boolean;
  restricted: boolean;
  isTemplate: boolean;
  templateVariables: string;
  publishedAt: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  commentsEnabled: boolean;
  imageOptimized: ImageOptimized;
  iconOptimized: ImageOptimized;
  headerImageOptimized: ImageOptimized;
};

type Series = {
  id: string;
  ticker: string;
  slug: string;
  title: string;
  subtitle: string;
  seriesType: string;
  recurrence: string;
  description: string;
  image: string;
  icon: string;
  layout: string;
  active: boolean;
  closed: boolean;
  archived: boolean;
  new: boolean;
  featured: boolean;
  restricted: boolean;
  isTemplate: boolean;
  templateVariables: boolean;
  publishedAt: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  commentsEnabled: boolean;
  competitive: string;
  volume24hr: number;
  volume: number;
  liquidity: number;
  startDate: string;
  pythTokenID: string;
  cgAssetName: string;
  score: number;
  events: Array<Record<string, any>>; // Circular reference to Event
  collections: Collection[];
  categories: Category[];
  tags: Tag[];
  commentCount: number;
  chats: Chat[];
};

export type RawPolymarketEvent = {
  id: string;
  ticker: string;
  slug: string;
  title: string;
  subtitle: string;
  description: string;
  resolutionSource: string;
  startDate: string;
  creationDate: string;
  endDate: string;
  image: string;
  icon: string;
  active: boolean;
  closed: boolean;
  archived: boolean;
  new: boolean;
  featured: boolean;
  restricted: boolean;
  liquidity: number;
  volume: number;
  openInterest: number;
  // TODO: Find out what the other possible values are
  sortBy?: 'price';
  category: string;
  subcategory: string;
  isTemplate: boolean;
  templateVariables: string;
  published_at: string;
  createdBy: string;
  updatedBy: string;
  createdAt: string;
  updatedAt: string;
  commentsEnabled: boolean;
  competitive: number;
  volume24hr: number;
  volume1wk: number;
  volume1mo: number;
  volume1yr: number;
  featuredImage: string;
  disqusThread: string;
  parentEvent: string;
  enableOrderBook: boolean;
  liquidityAmm: number;
  liquidityClob: number;
  negRisk: boolean;
  negRiskMarketID: string;
  negRiskFeeBips: number;
  commentCount: number;
  imageOptimized: ImageOptimized;
  iconOptimized: ImageOptimized;
  featuredImageOptimized: ImageOptimized;
  subEvents: string[];
  markets: RawPolymarketMarket[];
  series: Series[];
  categories: Category[];
  collections: Collection[];
  tags: Tag[];
  cyom: boolean;
  closedTime: string;
  showAllOutcomes: boolean;
  showMarketImages: boolean;
  automaticallyResolved: boolean;
  enableNegRisk: boolean;
  automaticallyActive: boolean;
  eventDate: string;
  startTime: string;
  eventWeek: number;
  seriesSlug: string;
  score?: string;
  elapsed?: string;
  period?: string;
  live: boolean;
  ended?: boolean;
  finishedTimestamp: string;
  gmpChartMode: string;
  eventCreators: EventCreator[];
  tweetCount: number;
  chats: Chat[];
  featuredOrder: number;
  estimateValue: boolean;
  cantEstimate: boolean;
  estimatedValue: string;
  templates: Template[];
  /**
   * TODO: These are not getting returned, ask Polymarket team why
   */
  spreadsMainLine?: number;
  totalsMainLine?: number;
  carouselMap: string;
  pendingDeployment: boolean;
  deploying: boolean;
  deployingTimestamp: string;
  scheduledDeploymentTimestamp: string;
  gameStatus: string;
  gameId?: number;
  homeTeamName?: string;
  awayTeamName?: string;
};

export type PolymarketEvent = Omit<RawPolymarketEvent, 'markets'> & {
  markets: PolymarketMarket[];
  color: string;
  teams?: PolymarketTeamInfo[];
};

/**
 * This is a simplified version of the RawPolymarketEvent that is attached to the RawPolymarketMarket
 * ie. market = { ...market, events: [PolymarketMarketEvent] }
 */
export type PolymarketMarketEvent = {
  id: string;
  ticker: string;
  slug: string;
  title: string;
  description: string;
  resolutionSource: string;
  startDate: string;
  creationDate: string;
  endDate: string;
  image: string;
  icon: string;
  active: boolean;
  closed: boolean;
  closedTime?: string;
  archived: boolean;
  new: boolean;
  featured: boolean;
  restricted: boolean;
  liquidity: number;
  volume: number;
  openInterest: number;
  sortBy: string;
  createdAt: string;
  updatedAt: string;
  competitive: number;
  volume24hr: number;
  volume1wk: number;
  volume1mo: number;
  volume1yr: number;
  enableOrderBook: boolean;
  liquidityClob: number;
  negRisk: boolean;
  negRiskMarketID: string;
  commentCount: number;
  cyom: boolean;
  showAllOutcomes: boolean;
  showMarketImages: boolean;
  startTime?: string;
  enableNegRisk: boolean;
  gmpChartMode: string;
  negRiskAugmented: boolean;
  pendingDeployment: boolean;
  deploying: boolean;
  deployingTimestamp: string;
  gameId?: number;
  color: string;
  ended?: boolean;
  live?: boolean;
  period?: string;
  score?: string;
  elapsed?: string;
  teams?: PolymarketTeamInfo[];
};

export type RawPolymarketOptimizedMarket = {
  active: boolean;
  archived: boolean;
  bestAsk: number;
  bestBid: number;
  closed: boolean;
  groupItemTitle: string;
  lastTradePrice: number;
  outcomePrices: string[];
  outcomes: string[];
  question: string;
  slug: string;
  spread: number;
};

export type RawPolymarketOptimizedEvent = {
  markets: RawPolymarketOptimizedMarket[];
  active: boolean;
  archived: boolean;
  closed: boolean;
  endDate: string;
  ended: boolean;
  id: string;
  image: string;
  negRisk: boolean;
  slug: string;
  startDate: string;
  title: string;
};

export type PolymarketOptimizedEvent = RawPolymarketOptimizedEvent & {
  color: string;
};
