nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.2.2.cjs
enableScripts: false
checksumBehavior: reset
defaultSemverRangePrefix: ''
enableInlineBuilds: true

npmScopes:
  rainbow-me:
    npmRegistryServer: 'https://registry.npmjs.org'
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN}'
