export enum AssetType {
  arbitrum = 'arbitrum',
  base = 'base',
  bsc = 'bsc',
  compound = 'compound',
  eth = 'eth',
  nft = 'nft',
  optimism = 'optimism',
  polygon = 'polygon',
  zora = 'zora',
  token = 'token',
  trash = 'trash',
  uniswap = 'uniswap',
  uniswapV2 = 'uniswap-v2',
  zkSync = 'zkSync',
}

export default {
  arbitrum: 'arbitrum',
  base: 'base',
  bsc: 'bsc',
  compound: 'compound',
  eth: 'eth',
  nft: 'nft',
  optimism: 'optimism',
  polygon: 'polygon',
  zora: 'zora',
  token: 'token',
  trash: 'trash',
  uniswap: 'uniswap',
  uniswapV2: 'uniswap-v2',
  zkSync: 'zkSync',
} as const;
