export enum ProtocolType {
  aave = 'aave',
  bancor = 'bancor',
  compound = 'compound',
  curve = 'curve',
  disperse_app = 'disperse_app',
  dsr = 'dsr',
  dydx = 'dydx',
  fulcrum = 'fulcrum',
  iearn = 'iearn',
  kyber = 'kyber',
  maker = 'maker',
  maker_dss = 'maker_dss',
  one_inch = 'one_inch',
  pool_together = 'pool_together',
  ray = 'ray',
  set = 'set',
  synthetix = 'synthetix',
  uniswap = 'uniswap',
  zrx_stacking = 'zrx_stacking',
  zrx_staking = 'zrx_staking',
}

export default {
  [ProtocolType.aave]: 'Aave',
  [ProtocolType.bancor]: 'Bancor',
  [ProtocolType.compound]: 'Compound',
  [ProtocolType.curve]: 'Curve',
  [ProtocolType.disperse_app]: 'Disperse',
  [ProtocolType.dsr]: 'DSR',
  [ProtocolType.dydx]: 'dYdX',
  [ProtocolType.fulcrum]: 'Fulcrum',
  [ProtocolType.iearn]: 'iEarn Finance',
  [ProtocolType.kyber]: 'Kyber',
  [ProtocolType.maker]: 'Maker', // old maker
  [ProtocolType.maker_dss]: 'Maker',
  [ProtocolType.one_inch]: '1inch',
  [ProtocolType.pool_together]: 'Pool Together',
  [ProtocolType.ray]: 'Ray',
  [ProtocolType.set]: 'Set Protocol',
  [ProtocolType.synthetix]: 'Synthetix',
  [ProtocolType.uniswap]: 'Uniswap',
  [ProtocolType.zrx_stacking]: '0x Staking', // this is here for now due to a typo from Zerion field
  [ProtocolType.zrx_staking]: '0x Staking',
};
