export default {
  approved: 'approved',
  approving: 'approving',
  depositing: 'depositing',
  failed: 'failed',
  received: 'received',
  receiving: 'receiving',
  savingsDeposit: 'savingsDeposit',
  savingsWithdrawal: 'savingsWithdrawal',
  self: 'self',
  sending: 'sending',
  sent: 'sent',
  swapped: 'swapped',
  unknown: 'unknown status',
  withdrawing: 'withdrawing',
};
