export default {
  approved: 'approved',
  approving: 'approving',
  cancelled: 'cancelled',
  cancelling: 'cancelling',
  deposited: 'deposited',
  depositing: 'depositing',
  failed: 'failed',
  purchased: 'purchased',
  purchasing: 'purchasing',
  received: 'received',
  receiving: 'receiving',
  self: 'self',
  sending: 'sending',
  sent: 'sent',
  speeding_up: 'speeding up',
  swapped: 'swapped',
  swapping: 'swapping',
  unknown: 'unknown status',
  withdrawing: 'withdrawing',
  withdrew: 'withdrew',
};
