source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '>= 2.7.0'

gem "fastlane"
# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '1.16.2'
gem 'activesupport', '>= 6.1.7.5', '<7.1.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
