platform :ios, '9.0'

target 'BalanceWallet' do
  rn_path = '../node_modules/react-native'
  pod 'Firebase/Core', '~> 5.3.0'
  pod 'Firebase/Messaging', '~> 5.3.0'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTImage'
  ]
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'RNLanguages', :path => '../node_modules/react-native-languages'
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
end
