# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Refresh dSYMs"
  lane :refresh_dsyms do
    download_dsyms(version: "latest")
    upload_symbols_to_crashlytics
    sentry_upload_dsym
    sentry_create_release(
      finalize: true # Whether to finalize the release. If not provided or false, the release can be finalized using the sentry_finalize_release action
    )
    sentry_upload_sourcemap(
      sourcemap: './main.jsbundle', # file to upload
      rewrite: true
    )
    sentry_upload_sourcemap(
      sourcemap: './main.jsbundle.map', # sourcemap to upload
      rewrite: true
    )
    clean_build_artifacts
  end

  desc "Submit a new Beta build to Apple TestFlight"
  lane :beta do
    increment_build_number({
      build_number: latest_testflight_build_number + 1
    })

    update_info_plist(
      plist_path: "Rainbow/Info.plist",
      display_name: "Rainbow"
    )
    update_app_identifier(
      app_identifier: "me.rainbow",
      xcodeproj: "Rainbow.xcodeproj",
      plist_path: "Rainbow/Info.plist",
    )
    match(
      type: "appstore",
      app_identifier: "me.rainbow",
      git_url: "git@github.com:rainbow-me/rainbow-code-signing.git"
    )
    gym(
      scheme: "Rainbow",
      export_method: "app-store",
      include_symbols: true,
    )
    pilot(
      app_identifier: "me.rainbow"
    )
    refresh_dsyms
  end
end
