# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Refresh dSYMs"
  lane :refresh_dsyms do
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end

  desc "Submit a new Beta build to Apple TestFlight"
  lane :beta do
    update_info_plist(
      plist_path: "BalanceWallet/Info.plist",
      display_name: "Balance"
    )
    update_app_identifier(
      app_identifier: "io.balance.balancewallet",
      xcodeproj: "BalanceWallet.xcodeproj",
      plist_path: "BalanceWallet/Info.plist",
    )
    match(
      type: "appstore",
      app_identifier: "io.balance.balancewallet",
      git_url: "git@github.com:balance-io/balance-code-signing.git"
    )
    gym(
      scheme: "BalanceWallet",
      export_method: "app-store",
      include_symbols: true,
    )
    pilot(
      app_identifier: "io.balance.balancewallet"
    )
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end

  desc "Submit a new Internal build to Apple TestFlight"
  lane :internal do
    update_info_plist(
      plist_path: "BalanceWallet/Info.plist",
      display_name: "Internal"
    )
    update_app_identifier(
      app_identifier: "io.balance.balancewallet.internal",
      xcodeproj: "BalanceWallet.xcodeproj",
      plist_path: "BalanceWallet/Info.plist",
    )
    match(
      type: "appstore",
      app_identifier: "io.balance.balancewallet.internal",
      git_url: "git@github.com:balance-io/balance-code-signing.git"
    )
    gym(
      scheme: "BalanceWallet",
      export_method: "app-store",
      include_symbols: true,
    )
    pilot(
      app_identifier: "io.balance.balancewallet.internal"
    )
    download_dsyms
    upload_symbols_to_crashlytics
    clean_build_artifacts
  end
end
