# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :bump_version_code do
    path = '../app/build.gradle'
    re = /versionCode\s+(\d+)/ 
  
    s = File.read(path)
    versionCode = s[re, 1].to_i
    s[re, 1] = (versionCode + 1).to_s
  
    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  lane :internal do
    gradle(task: 'bundle', build_type: 'Release')
    upload_to_play_store(track: 'internal')
  end

  lane :alpha do
    gradle(task: 'bundle', build_type: 'Release')
    upload_to_play_store(track: 'alpha')
  end
  
  lane :beta do
    gradle(task: 'bundle', build_type: 'Release')
    upload_to_play_store(track: 'beta')
  end

  desc "Deploy a new version to the Google Play"
  lane :production do
    versionCode = bump_version_code()
    gradle(task: 'clean')
    gradle(task: 'bundle', build_type: 'Release', properties: { 'versionCode' => versionCode})
    upload_to_play_store(json_key: "./rainbow-google-play-key.json")
  end

end
