# This is a basic workflow to help you get started with Actions

name: "clear-cache"
description: 'Clear macstadium cache on a specific instance'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - id: clean
      shell: bash
      run: |
        yarn nuke
        detox clean-framework-cache && detox build-framework-cache

