name: Android e2e tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  android-e2e-build:
    if: github.event.pull_request.draft == false
    runs-on: blacksmith-8vcpu-ubuntu-2404
    timeout-minutes: 30
    concurrency:
      group: e2e-android-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      artifact-id: ${{ steps.rnef-remote-build-android.outputs.artifact-id }}

    env:
      # Can be used to help debug test failures. This will cause the apk to be
      # This is a debug keystore for now.
      KEYSTORE_BASE64: '/u3+7QAAAAIAAAABAAAAAQAPYW5kcm9pZGRlYnVna2V5AAABQ0rLwugAAAUCMIIE/jAOBgorBgEEASoCEQEBBQAEggTqTrf+4E+GStFgPoOC61gnr9bB/F+5FoOnyI/HfwxSOdr5lix4SidLflxqyfw62LKC+H2LAlUpURtdItvcf5/VoQIhgAnIiOXuw5mKEu6dRqw1r0ifeNZB5lyEUKAptdJA5R1JwnPdZJeWPvoyI20B89eZAvSDai84cPPLIiwiyIGoiXxcuNXQ9DFlGrs3ryECxeAVjbhoKIyf9+EuoUZpNdUXu2+GmXVuAWfCKr8hAc3L7K3L23ZGD+cVzdaqilNiIZoOq1TeyTTSGg2vUA08R5XMkYc4nYHNKI/H1achWmQiBgPoGnuKCGum294nXysg8Wux8Qw1b/kcPjmrUi4rNLUvdzNZG5RzyUJ5voIDr/jR8+IwKEoOnilwQuRnzJ2B3VK5XctoCxxULj/HMJ+T7ZLes+jG72tHZ+A99C/ZAxjhtvbvpwkOXlGX/cMR8yIuHU+HUcKWxZfSGIbCAVG1rpVZZysYOBa0+WasJcYA1iJgq1Zm9mKquL4ZTaY2aFerEnGgdMPu/Vt4o9OAHoCqJVxsqMCoWFbxDuf7dX06jgg5jQbIJytO47b4Nzp6XKGdNJcRI78Cnw2UCN9BvkeYmubdmExKYWTvyMmT4M/3ycR7dGJQu9Ge4GzKiUR97kmzGbqPyW0748mII7F0D/o2EARHojshdxGpF99iQOx4ZhwpgUf8RUH/DH81WDggDOGXA3NFf18EPy9mi6Epzfd56COS+X7uRVppV8z2TPuZbWqlmTkp++BMcG8YQhMISUBmwF11+kOB3wf9/DhnfzFCNNbL2Tno7AS4k+NiAgwsyOLWLGLOIIM7mWmDmeOe4SC2IwSnzwa7XiPNHWSTy6L/wIl+5Dx3JUpFrboWDFadMWS4+uMvqf89lataom+kCGye7f1KQzLI5Tg1niU4E2rtb7TRVYQp2PW3oC1uRX0xKB/cEYfhJYqH6TAx2gktIRxJpcNaesZnoAZsNeHgystWxEB2ga3BnD6rG4N41lYBd0x3X6H8yU7D3dNv2Gk3RYYvliiivMRm7DDauGzC0NuFbNvfT26DY9G+HK5kFDjhLEryEQYmTrHPSWjBt1xwTV6KmdF73Hr/+n9UgVqq2rPEcq8bdRbnviiq2fczHHLfPLa5Wba0Af7kDks9jQ+4VpxFBa5v5WWxznXHs+R6tyJkI3gfl2XSe2/y4PHyXDXfb7ABddj0aYhudhRX2eOtQCXH+Dl6/edD5kM69P6GGm1OCEGrgTha13pJF67mZs5TDpoEKBXTnXtyMjky1XCOf3uscE8nKSC7Exy5bTVWG4pMobdbY4HVklRksvGfD50NJ+XuIBtwPg8q5lKWHMEwPk5I9aRjxdbWJ0v82RkCkmRwr1rVa2yIPU5tGksLV6HIp5oSxynOOe7S2sm0QA866KcNowNsm2PB+8Z+vL4QtQ+chdkL7vRHRqsWS49g7a4g7+oY7PR8H67o9D2QF6ea4pYzE1AXKpwuEqi3XHZV1JFki5Gwt9h8tMdIibkFpRt4i6oyvNIaBQXY93CrWufAZ6rJRYnGiCNms3JL8Ovh9UaztEQ4qyLFCA0DVimGbnzu+OOXyrTqMagEBCjSb6IkSsntoeVhg+69XHMM3aY4jyReQCT/UQuVLvB2S930BETqCWWML8GW7aS1jOFRR572Csu6k9Rzso7qyVmAcQAAAAEABVguNTA5AAADfzCCA3swggJjoAMCAQICBCMurmIwDQYJKoZIhvcNAQEFBQAwbTELMAkGA1UEBhMCVVMxEDAOBgNVBAgTB1Vua25vd24xEDAOBgNVBAcTB1Vua25vd24xEDAOBgNVBAoTB1Vua25vd24xEDAOBgNVBAsTB0FuZHJvaWQxFjAUBgNVBAMTDUFuZHJvaWQgRGVidWcwIBcNMTMxMjMxMjIzNTA0WhgPMjA1MjA0MzAyMjM1MDRaMG0xCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdVbmtub3duMRAwDgYDVQQHEwdVbmtub3duMRAwDgYDVQQKEwdVbmtub3duMRAwDgYDVQQLEwdBbmRyb2lkMRYwFAYDVQQDEw1BbmRyb2lkIERlYnVnMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkt5uICbIbNVEHniMJfQNW9zRd7rXemfDAn3P6K0WP9UVXqRTa1i+GZk2nscWZ3CBhQgdNc3suXEkxOzKzXbhlkKG4IwFiq0v5/g02tFYhAdaW/VIN4dXa/VYh/yYM/s9IZ0pNvFQuYG5OeutT+fZtWHiCFcR04hFSSzUupqrQV+yG4KkddgFc2mH+xc+wMtX8eLmQNmPLeHe6ScAFbDoYzhd2/u2m4fcVQFKiio1WRnRfRVjBbbmsefuAkpxjIkHCJJiQH/UQ95H7/LaSNd0eSsg35MhgEPfmV3NQjdpgMYr/S0jw0+4vi5wrZaGJXgKDuipRUly1E2xJfCG3+nRYQIDAQABoyEwHzAdBgNVHQ4EFgQUC/n+OInSipxY8MEKtw5DKNgj8yAwDQYJKoZIhvcNAQEFBQADggEBAF/SdhW/zmMYTRJQwbkRdfC84vnETnrnd3+NhcnhshU9PRAGa7ABmiwKbX48Atvf93bWtv8nLrz0aCWYaKQMDnfUMEVee8/Duf8vT3qKkxt1sFK79CRfMeKOD0kQGKt+l9f7jh1z0xLNCNyW+53Tk5yi4dat9lz/SljZ7JFq6gbUO1JD+tWc8RRuPHGrZtMk8BKTWjFOlq/4G67Bg8g3kPmahtq1a1vFsm0WlLw1XkKQ7ALtuhFdV7vdZaiw5Gk0VrWsKjoHpER+XXrU3p38ipnFPNTubC5lub/exomujiMZ1ky4OmMIohh+MMA/7vaHcY1JA+VAA6mgtX9429moiSpJHNfTl/MPnoJZYANHJ0BedwjxBQ=='
      KEYSTORE_FILE: 'debug.keystore'
      KEYSTORE_PASSWORD: 'android'
      KEYSTORE_KEY_ALIAS: 'androiddebugkey'
      KEYSTORE_KEY_PASSWORD: 'android'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install secret tools
        run: sudo apt install libsecret-tools

      - name: Setup env key
        uses: ./.github/actions/ssh/
        with:
          name: env
          key: ${{ secrets.DEPLOY_PKEY_DOTENV_REPO }}

      - name: Setup scripts key
        uses: ./.github/actions/ssh/
        with:
          name: scripts
          key: ${{ secrets.DEPLOY_PKEY_SCRIPTS_REPO }}

      - name: Setup sandbox key
        uses: ./.github/actions/ssh/
        with:
          name: sandbox
          key: ${{ secrets.DEPLOY_PKEY_SANDBOX_REPO }}

      - name: Setup env
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent_env.sock
        run: |
            git clone git@github.com:rainbow-me/rainbow-env.git
            mv rainbow-env/dotenv .env
            mv rainbow-env/android/app/google-services.json android/app/google-services.json
            rm -rf rainbow-env
            sed -i "s/IS_TESTING=false/IS_TESTING=true/" .env
      - name: Setup scripts
        env:
            CI_SCRIPTS: ${{ secrets.CI_SCRIPTS }}
            SSH_AUTH_SOCK: /tmp/ssh_agent_scripts.sock
        run: |
            eval $CI_SCRIPTS
      - name: Get Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - name: Cache Yarn dependencies
        uses: useblacksmith/cache@v5
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            .yarn/cache
            .yarn/install-state.gz
          key: ${{ runner.os }}-${{ runner.arch }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Checkout Janic branch for now
        run: cd rainbow-scripts && git checkout @janic/rn79

      - name: Install dependencies
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent_sandbox.sock
        run: |
          yarn install && yarn setup

      - name: Check for frozen lockfile
        run: ./scripts/check-lockfile.sh

      - name: Audit CI
        run: yarn audit-ci --config audit-ci.jsonc

      - name: RNEF Remote Build - Android
        id: rnef-remote-build-android
        uses: callstackincubator/android@v1
        with:
          variant: release
          sign: true
          keystore-base64: ${{ env.KEYSTORE_BASE64 }}
          keystore-store-file: ${{ env.KEYSTORE_FILE }}
          keystore-store-password: ${{ env.KEYSTORE_PASSWORD }}
          keystore-key-alias: ${{ env.KEYSTORE_KEY_ALIAS }}
          keystore-key-password: ${{ env.KEYSTORE_KEY_PASSWORD }}
          re-sign: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          validate-gradle-wrapper: false
          rnef-build-extra-params: '--extra-params="-PisE2E=true --no-daemon --build-cache --no-scan" --verbose'
          comment-bot: false

  android-e2e-tests:
    strategy:
      fail-fast: false
      matrix:
        shard-index: [1, 2, 3, 4]
    if: github.event.pull_request.draft == false
    runs-on: app-e2e-runner
    needs: android-e2e-build
    timeout-minutes: 30
    concurrency:
      group: e2e-android-${{ github.workflow }}-${{ github.ref }}-shard-${{ matrix.shard-index }}
      cancel-in-progress: false

    env:
      # Can be used to help debug test failures. This will cause the apk to be
      # built for all architectures so it can be downloaded from the artifacts
      # and installed locally. It will also record logcat logs and a video of
      # the test run. Note that the video is limited to 3 minutes.
      DEBUG: false
      SHARD_TOTAL: 4
      SHARD_INDEX: ${{ matrix.shard-index }}
      ANDROID_EMULATOR_API_LEVEL: 31
      ANDROID_EMULATOR_PROFILE: pixel_6
      ANDROID_EMULATOR_CORES: 4
      ANDROID_EMULATOR_RAM_SIZE: 8192
      ARTIFACTS_FOLDER: e2e-artifacts
      ARCH: x86_64
      ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup env key
        uses: ./.github/actions/ssh/
        with:
          name: env
          key: ${{ secrets.DEPLOY_PKEY_DOTENV_REPO }}

      - name: Setup env
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent_env.sock
        run: |
            git clone git@github.com:rainbow-me/rainbow-env.git
            mv rainbow-env/dotenv .env
            rm -rf rainbow-env

      - name: Install Maestro
        run: export MAESTRO_VERSION=1.41.0; curl -fsSL "https://get.maestro.mobile.dev" | bash

      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Download and Unpack APK artifact
        run: |
          curl -L -H "Authorization: token ${{ github.token }}" -o artifact.zip "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ needs.android-e2e-build.outputs.artifact-id }}/zip"
          unzip artifact.zip -d downloaded-artifacts
          ls -l downloaded-artifacts
          APK_PATH=$(find downloaded-artifacts -name "*.apk" -print -quit)
          echo "ARTIFACT_PATH_FOR_E2E=$APK_PATH" >> $GITHUB_ENV
        shell: bash

      - name: Setup Android Emulator
        id: android-emulator
        uses: ./.github/actions/android-emulator/
        with:
          api-level: ${{ env.ANDROID_EMULATOR_API_LEVEL }}
          profile: ${{ env.ANDROID_EMULATOR_PROFILE }}
          cores: ${{ env.ANDROID_EMULATOR_CORES }}
          ram-size: ${{ env.ANDROID_EMULATOR_RAM_SIZE }}
          arch: ${{ env.ARCH }}

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        id: e2e_test
        with:
          api-level: ${{ env.ANDROID_EMULATOR_API_LEVEL }}
          target: google_apis_playstore
          arch: ${{ env.ARCH }}
          force-avd-creation: false
          emulator-options: -no-snapshot -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          profile: ${{ env.ANDROID_EMULATOR_PROFILE }}
          cores: ${{ env.ANDROID_EMULATOR_CORES }}
          ram-size: ${{ env.ANDROID_EMULATOR_RAM_SIZE }}
          script: ./scripts/e2e-android-ci.sh

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.shard-index }}
          path: ${{ env.ARTIFACTS_FOLDER }}
