name: iOS Builds
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-simulator:
    name: Simulator
    runs-on: macos-26-xlarge
    env:
      NODE_OPTIONS: '--max-old-space-size=6144'
    timeout-minutes: 45
    if: github.event.pull_request.draft == false && github.event.pull_request.merged == false
    concurrency:
      group: ${{ github.workflow }}-simulator-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      artifact-id: ${{ steps.build.outputs.artifact-id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build
        id: build
        uses: ./.github/actions/ios-build
        with:
          destination: simulator
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-pkey-dotenv: ${{ secrets.DEPLOY_PKEY_DOTENV_REPO }}
          deploy-pkey-scripts: ${{ secrets.DEPLOY_PKEY_SCRIPTS_REPO }}
          deploy-pkey-sandbox: ${{ secrets.DEPLOY_PKEY_SANDBOX_REPO }}
          ci-scripts: ${{ secrets.CI_SCRIPTS }}

  build-device:
    name: Device
    runs-on: macos-26-xlarge
    env:
      NODE_OPTIONS: '--max-old-space-size=6144'
    timeout-minutes: 45
    if: github.event.pull_request.draft == false && github.event.pull_request.merged == false
    concurrency:
      group: ${{ github.workflow }}-device-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      artifact-id: ${{ steps.build.outputs.artifact-id }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build
        id: build
        uses: ./.github/actions/ios-build
        with:
          destination: device
          sentry-auth-token: ${{ secrets.SENTRY_AUTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-pkey-dotenv: ${{ secrets.DEPLOY_PKEY_DOTENV_REPO }}
          deploy-pkey-scripts: ${{ secrets.DEPLOY_PKEY_SCRIPTS_REPO }}
          deploy-pkey-sandbox: ${{ secrets.DEPLOY_PKEY_SANDBOX_REPO }}
          ci-scripts: ${{ secrets.CI_SCRIPTS }}
          deploy-pkey-codesigning: ${{ secrets.DEPLOY_PKEY_CODE_SIGNING_REPO }}
          fastlane-user: ${{ secrets.FASTLANE_USER }}
          fastlane-password: ${{ secrets.FASTLANE_PASSWORD }}
          match-password: ${{ secrets.MATCH_PASSWORD }}
          apple-build-certificate-password: ${{ secrets.APPLE_BUILD_CERTIFICATE_PASSWORD }}
          apple-keychain-password: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}

  # Post builds to GitHub after both complete
  post-builds:
    name: Post Builds
    needs: [build-simulator, build-device]
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && needs.build-simulator.result == 'success' && needs.build-device.result == 'success'
    steps:
      - name: Download simulator artifact
        run: |
          curl -L -H "Authorization: token ${{ github.token }}" -o simulator-artifact.zip "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ needs.build-simulator.outputs.artifact-id }}/zip"
          unzip simulator-artifact.zip -d simulator-artifacts
          APP_ARCHIVE_PATH=$(find simulator-artifacts -name "*.tar.gz" -print -quit)
          tar -xzf "$APP_ARCHIVE_PATH" -C simulator-artifacts
          APP_PATH=$(find simulator-artifacts -name "*.app" -type d | head -n 1)
          cd "$APP_PATH" && zip -r "${{ github.workspace }}/simulator-app.zip" .

      - name: Download device artifact
        run: |
          curl -L -H "Authorization: token ${{ github.token }}" -o device-artifact.zip "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ needs.build-device.outputs.artifact-id }}/zip"
          unzip device-artifact.zip -d device-artifacts
          IPA_PATH=$(find device-artifacts -name "*.ipa" | head -n 1)
          cp "$IPA_PATH" ./device-app.ipa

      - name: Upload builds to AWS S3
        env:
          AWS_BUCKET: rainbow-app-team-production
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          aws s3 cp "simulator-app.zip" "s3://${AWS_BUCKET}/${BRANCH_NAME}/${COMMIT_HASH}.app.zip"
          aws s3 cp "device-app.ipa" "s3://${AWS_BUCKET}/${BRANCH_NAME}/${COMMIT_HASH}.ipa"

      - name: Post comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          COMMENT="Launch in [simulator](http://localhost:29070/install/http?url=https://app-team.p.rainbow.me/${BRANCH_NAME}/${COMMIT_HASH}.app.zip&platform=ios&destination=simulator) or [device](http://localhost:29070/install/http?url=https://app-team.p.rainbow.me/${BRANCH_NAME}/${COMMIT_HASH}.ipa&platform=ios&destination=device) for ${COMMIT_HASH}"
          curl -s -H "Authorization: token $GITHUB_TOKEN" -X POST \
          -d "{\"body\":\"$COMMENT\"}" \
          "${{ github.event.pull_request.comments_url }}"
