# This is a basic workflow to help you get started with Actions

name: Clear macstadium cache (Single instance)

# Controls when the workflow will run
on: [ workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "clear-cache-single-instance"
  clear-cache-single-instance:
    # The type of runner that the job will run on
    runs-on: ["self-hosted"]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up github keys
        run: git config core.sshCommand "ssh -i ~/.ssh/id_ed25519 -F /dev/null"

      - name: Clean cache
        run: yarn nuke

      - name: Rebuild detox framework cache
        run: detox clean-framework-cache && detox build-framework-cache

      - name: Send success message to slack
        id: slack-success-msg
        uses: slackapi/slack-github-action@v1.21.0
        if: ${{ job.status == 'success' }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Cache cleared on macstadium. Author: ${{ github.actor }}\nStatus: ✅  ${{ job.status }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                      {
                          "type": "button",
                          "text": {
                              "type": "plain_text",
                              "text": "View Pull Request",
                              "emoji": true
                          },
                          "url": "${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                      },
                      {
                          "type": "button",
                          "text": {
                              "type": "plain_text",
                              "text": "View Build",
                              "emoji": true
                          },
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
      - name: Send error message to slack
        id: slack-error-msg
        uses: slackapi/slack-github-action@v1.21.0
        if: ${{ job.status != 'success' }}
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Cache cleaning job }\nAuthor: ${{ github.actor }}\nStatus: ❌  ${{ job.status }}"
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "actions",
                  "elements": [
                      {
                          "type": "button",
                          "text": {
                              "type": "plain_text",
                              "text": "View Job",
                              "emoji": true
                          },
                          "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
