name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '30 20 * * 1'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Stale issue message'
        stale-issue-label: 'no-issue-activity'
