name: Unit tests

on: [pull_request]

permissions: {}

jobs:
  lint-and-unit-test:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: read
    env:
      NODE_OPTIONS: '--max-old-space-size=6144'
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup workspace
        uses: ./.github/actions/setup
        with:
          deploy-pkey-dotenv: ${{ secrets.DEPLOY_PKEY_DOTENV_REPO }}
          deploy-pkey-scripts: ${{ secrets.DEPLOY_PKEY_SCRIPTS_REPO }}
          deploy-pkey-sandbox: ${{ secrets.DEPLOY_PKEY_SANDBOX_REPO }}
          ci-scripts: ${{ secrets.CI_SCRIPTS }}
          google-services: 'true'
          is-testing: 'true'

      - name: Audit CI
        run: yarn audit-ci --config audit-ci.jsonc

      - name: Remove ESLint cache
        run: rm -f .eslintcache

      - name: Lint
        run: yarn lint:ci

      - name: Unit tests
        run: yarn test
